### ISSUE TITLE
Unknow VRAM

### ISSUE THREAD

**Issue by Joe-Lapetoire** [emeric254/PyHawaiiBiosReader#12]
Hello, i have this problem :
unknow VRM : 0x9608 @ 0xaea4
unknow VRM : 0x60 @ 0xaea6
unknow VRM : 0x0 @ 0xaea8
unknow VRM : 0x0 @ 0xaeaa
unknow VRM : 0x4b @ 0xaeac
unknow VRM : 0x7b @ 0xaeae
unknow VRM : 0x3 @ 0xaeb2
unknow VRM : 0x39 @ 0xaeb4
unknow VRM : 0xaa @ 0xaeb6
unknow VRM : 0xff @ 0xaeb8
unknow VRM : 0x701 @ 0xaeba

(Bios of Saphir R9 390X - Same issue with "tri-x or nitro" bios).
Can you help me ?

Thanks

**Comment by emeric254** [comment]
I get offset from the original project there : https://github.com/OneB1t/HawaiiBiosReader

I encounter some of this error too on my 290x bios files, I choose to keep them shown as "unknown VRM" to track them if you want to do further manual edits (with a manual hex editor)
